### ISSUE TITLE
can't figure out how to use this module from a task inside my own role

### ISSUE THREAD

**Issue by maspotts** [yutannihilation/ansible-module-cran#4]
Hi: thanks for writing this module (role)?  It's working great for me when I call it from my playbook.  But I can't figure out how to move it into a role.  Here's my playbook (excerpt):

```
- hosts: mac
  roles:
    - yutannihilation.module-cran
  environment:
    PATH: /opt/brew/bin:{{ ansible_env.PATH }}
  tasks:
    - name: Install R packages
      cran: name={{ item }} state=present
      with_items:
        - tuneR
        - seewave
```
and here's my best guess at making this part of my role (tasks/main.yml):

```
- name: Install the R packages
  yutannihilation.module-cran: name={{ item }} state=present
  with_items:
    - tuneR
    - seewave
  environment:
    PATH: /opt/brew/bin:{{ ansible_env.PATH }}
```

but it can't recognise the module (although it was installed successfully via ansible-galaxy, since it works from the playbook):
```
ERROR! couldn't resolve module/action 'yutannihilation.module-cran'....
```

or if try this:

```
- name: Install the R packages
  yutannihilation.module-cran:
    name:
      - tuneR
      - seewave
    state: present
    environment:
      PATH: /opt/brew/bin:{{ ansible_env.PATH }}
```

then again:

```
ERROR! couldn't resolve module/action 'yutannihilation.module-cran'
```

I tried lots of other variations, but none worked.  I'm afraid I'm a neophyte at ansible, and my googling so far has led to a dead end.  If you could show me how to make this work (calling this module from inside my role) I'll be very grateful!

Thanks!

**Comment by maspotts** [comment]
I did get this format to run (no errors) but also unfortunately doesn't actually do anything:

```

- name: Install AV dev R packages  # doesn't error but also doesn't do anything
  include_role:
    name: yutannihilation.module-cran
  vars:
    name: "{{ item }}"
    state: present
    environment:
      PATH: /opt/brew/bin:{{ ansible_env.PATH }}
  with_items:
    - tuneR
    - seewave
```

**Comment by maspotts** [comment]
I solved it: I had confused the role with the module.  Turns out I don't need to reference the role at all:

```
- name: Install AV dev R packages
  cran: name={{ item }} state=present
  with_items:
    - tuneR
    - seewave
  environment:
    PATH: "{{ homebrew_prefix }}/bin:{{ ansible_env.PATH }}"
```
